POST http://localhost:8080/api/students
Content-Type: application/json

{
  "name": "Dev sunar",
  "email": "dev@gmail.com",
  "phone": "9861915067",
  "hostel_id": "e5c32d5b-4636-44d8-9e87-5d43c9021137",
  "room_id": "c1a1eafd-e9bb-4592-ab84-10afdb3e8df3"
}