### Post request for hostel
POST http://localhost:8080/api/hostel
Authorization: Bearer
Content-Type: application/json

{
  "name": "Sagarmatha Boys  Hostel",
  "address": "Bharatpur",
  "wardenId": "4a7b3c2d-1e5f-4a3b-8c2d-1e5f4a3b2c1d"
}
