### Post request for staff
POST http://localhost:8080/api/staff
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiU1lTVEVNX0FETUlOIiwic3ViIjoiVGlsYWtia0BnbWFpbC5jb20iLCJpYXQiOjE3ODIxOTE3NTksImV4cCI6MTc4MjI3ODE1OX0.63CuJOZxUU-tDQ_HT4GuO_XUCwuaP1ouDbn8gTagtHA
Content-Type: application/json

{
  "name": "Binita@gmail.com",
  "email": "binita@gmail.com",
  "phone": "9840012345",
  "role": "WARDEN",
  "password": "Binita@123"
}

