### Create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Yasoda",
  "email": "alice.johnson@email.com",
  "address": "chitwan",
  "dateOfBirth": "2003-04-01",
  "registeredDate": "2016-04-01"
}